path:
  RAW_PATH: "./data/raw/"
  PROCESSED_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  image_size: 256
  batch_size: 16
  split_size: 0.25

attentionCNN:
  image_channels: 3
  image_size: 256
  nheads: 8
  dropout: 0.1
  activation: "relu"
  bias: True