stages:
  model_train:
    cmd: python src/cli.py --train
    deps:
      - src/cli.py
      - src/dataloader.py
      - src/decoder_block.py
      - src/encoder_block.py
      - src/feedforward_network.py
      - src/helper.py
      - src/loss/bce_loss.py
      - src/loss/combo_loss.py
      - src/dice_loss.py
      - src/focal_loss.py
      - src/jaccard_loss.py
      - src/mse_loss.py
      - src/mse_loss.py
      - src/tversky_loss.py
      - src/multihead_attention.py
      - src/scaled_dot_product.py
      - src/trainer.py
      - src/attentionCNNBlock.py
      - src/attentionCNN.py
      - src/utils.py
      - ./config.yml
      - ./data/
      - ./artifacts/

  model_eval:
    cmd: python src/cli.py --test
    deps:
      - src/cli.py
      - src/tester.py
      - src/attentionCNNBlock.py
      - src/attentionCNN.py